-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."DimDate"
(
    dateid integer NOT NULL,
    date date NOT NULL,
    "Year" integer NOT NULL,
    "Quarter" integer NOT NULL,
    "QuarterName" text NOT NULL,
    "Month" integer NOT NULL,
    "Monthname" text NOT NULL,
    "Day" integer NOT NULL,
    "Weekday" integer NOT NULL,
    "WeekdayName" text NOT NULL,
    PRIMARY KEY (dateid)
);

CREATE TABLE public."DimStation"
(
    "Stationid" integer NOT NULL,
    "City" character(20) NOT NULL,
    PRIMARY KEY ("Stationid")
);

CREATE TABLE public."DimTruck"
(
    "Truckid" integer NOT NULL,
    "TruckType" character(20) NOT NULL,
    PRIMARY KEY ("Truckid")
);

CREATE TABLE public."FactTrips"
(
    "Tripid" integer NOT NULL,
    "Dateid" integer,
    "Stationid" integer,
    "Truckid" integer,
    "Wastecollected" numeric,
    PRIMARY KEY ("Tripid")
);

ALTER TABLE public."FactTrips"
    ADD FOREIGN KEY ("Dateid")
    REFERENCES public."DimDate" (dateid)
    NOT VALID;


ALTER TABLE public."FactTrips"
    ADD FOREIGN KEY ("Dateid")
    REFERENCES public."DimDate" (dateid)
    NOT VALID;


ALTER TABLE public."FactTrips"
    ADD FOREIGN KEY ("Stationid")
    REFERENCES public."DimStation" ("Stationid")
    NOT VALID;


ALTER TABLE public."FactTrips"
    ADD FOREIGN KEY ("Truckid")
    REFERENCES public."DimTruck" ("Truckid")
    NOT VALID;

END;
